// Static trivia question pool. Korean only. Lunch-table tone — keep it light, avoid
// politics/religion/dated company info. Schema is immutable: id is a stable identifier
// used for replay/debug, never displayed.
//
// Adding questions: append to the array, give it a fresh id (kebab-case, descriptive).
// Don't reorder existing entries — server picks via seed-based shuffle, but the *pool*
// itself is sorted by id at runtime, so insertion order doesn't matter for determinism.

export type TriviaCategory = '한국상식' | '일반상식' | '과학' | '역사' | '문화';

export type TriviaQuestion = {
  id: string;
  category: TriviaCategory;
  question: string;
  choices: readonly [string, string, string, string];
  correctIndex: 0 | 1 | 2 | 3;
};

export const TRIVIA_POOL: readonly TriviaQuestion[] = [
  {
    id: 'kr-capital',
    category: '한국상식',
    question: '대한민국의 수도는?',
    choices: ['서울', '부산', '인천', '대전'],
    correctIndex: 0,
  },
  {
    id: 'kr-currency',
    category: '한국상식',
    question: '세종대왕이 만든 문자는?',
    choices: ['한자', '훈민정음', '이두', '향찰'],
    correctIndex: 1,
  },
  {
    id: 'kr-mountain',
    category: '한국상식',
    question: '한반도에서 가장 높은 산은?',
    choices: ['한라산', '지리산', '백두산', '설악산'],
    correctIndex: 2,
  },
  {
    id: 'kr-flag',
    category: '한국상식',
    question: '태극기 가운데 원의 빨간색이 의미하는 것은?',
    choices: ['땅', '음(陰)', '양(陽)', '하늘'],
    correctIndex: 2,
  },
  {
    id: 'world-largest-ocean',
    category: '일반상식',
    question: '세계에서 가장 큰 바다는?',
    choices: ['대서양', '인도양', '북극해', '태평양'],
    correctIndex: 3,
  },
  {
    id: 'world-longest-river',
    category: '일반상식',
    question: '세계에서 가장 긴 강은?',
    choices: ['나일강', '아마존강', '양쯔강', '미시시피강'],
    correctIndex: 0,
  },
  {
    id: 'world-tallest-mountain',
    category: '일반상식',
    question: '세계에서 가장 높은 산은?',
    choices: ['K2', '에베레스트', '킬리만자로', '몽블랑'],
    correctIndex: 1,
  },
  {
    id: 'world-eu-capital',
    category: '일반상식',
    question: '프랑스의 수도는?',
    choices: ['로마', '베를린', '파리', '마드리드'],
    correctIndex: 2,
  },
  {
    id: 'sci-water-formula',
    category: '과학',
    question: '물의 화학식은?',
    choices: ['CO₂', 'O₂', 'H₂', 'H₂O'],
    correctIndex: 3,
  },
  {
    id: 'sci-planet-count',
    category: '과학',
    question: '태양계 행성의 수는? (2006년 명왕성 분류 변경 이후)',
    choices: ['7개', '8개', '9개', '10개'],
    correctIndex: 1,
  },
  {
    id: 'sci-light-speed-unit',
    category: '과학',
    question: '빛의 속도와 가장 가까운 단위는?',
    choices: ['초속 30만km', '초속 3만km', '초속 300만km', '초속 3000km'],
    correctIndex: 0,
  },
  {
    id: 'sci-human-bones',
    category: '과학',
    question: '성인의 뼈 개수는 약 몇 개?',
    choices: ['106개', '156개', '206개', '256개'],
    correctIndex: 2,
  },
  {
    id: 'sci-blood-color',
    category: '과학',
    question: '사람 피의 빨간색을 만드는 단백질은?',
    choices: ['멜라닌', '헤모글로빈', '케라틴', '콜라겐'],
    correctIndex: 1,
  },
  {
    id: 'hist-hangeul',
    category: '역사',
    question: '한글이 반포된 해는?',
    choices: ['1446년', '1392년', '1592년', '1910년'],
    correctIndex: 0,
  },
  {
    id: 'hist-korea-war',
    category: '역사',
    question: '6·25 전쟁이 발발한 해는?',
    choices: ['1945년', '1948년', '1950년', '1953년'],
    correctIndex: 2,
  },
  {
    id: 'hist-joseon-founder',
    category: '역사',
    question: '조선을 건국한 인물은?',
    choices: ['왕건', '이성계', '정도전', '이방원'],
    correctIndex: 1,
  },
  {
    id: 'hist-ww2-end',
    category: '역사',
    question: '제2차 세계대전이 끝난 해는?',
    choices: ['1939년', '1941년', '1945년', '1950년'],
    correctIndex: 2,
  },
  {
    id: 'cult-olympic-rings',
    category: '문화',
    question: '올림픽 오륜기의 고리는 몇 개?',
    choices: ['4개', '5개', '6개', '7개'],
    correctIndex: 1,
  },
  {
    id: 'cult-mona-lisa',
    category: '문화',
    question: '"모나리자"를 그린 화가는?',
    choices: ['미켈란젤로', '레오나르도 다빈치', '라파엘로', '피카소'],
    correctIndex: 1,
  },
  {
    id: 'cult-shakespeare',
    category: '문화',
    question: '"햄릿"을 쓴 작가는?',
    choices: ['괴테', '톨스토이', '셰익스피어', '도스토옙스키'],
    correctIndex: 2,
  },
  {
    id: 'cult-bts-debut',
    category: '문화',
    question: 'BTS가 데뷔한 해는?',
    choices: ['2010년', '2013년', '2015년', '2017년'],
    correctIndex: 1,
  },
  {
    id: 'cult-kimchi-origin',
    category: '문화',
    question: '김치의 빨간 양념에 들어가는 핵심 재료는?',
    choices: ['고추가루', '간장', '된장', '카레가루'],
    correctIndex: 0,
  },
  {
    id: 'sci-fastest-animal',
    category: '과학',
    question: '지구상에서 가장 빠른 동물은?',
    choices: ['치타', '송골매', '말', '돌고래'],
    correctIndex: 1,
  },
  {
    id: 'kr-han-river-bridge',
    category: '한국상식',
    question: '서울 한강을 건너는 다리 중 가장 먼저 만들어진 다리는?',
    choices: ['반포대교', '한강대교', '성수대교', '동작대교'],
    correctIndex: 1,
  },
  {
    id: 'world-smallest-country',
    category: '일반상식',
    question: '세계에서 가장 작은 나라는?',
    choices: ['모나코', '바티칸시국', '산마리노', '리히텐슈타인'],
    correctIndex: 1,
  },
  {
    id: 'sci-dna-shape',
    category: '과학',
    question: 'DNA의 구조 모양은?',
    choices: ['직선', '나선형', '이중나선', '삼중나선'],
    correctIndex: 2,
  },
  {
    id: 'kr-traditional-clothes',
    category: '한국상식',
    question: '한국 전통 의상의 이름은?',
    choices: ['기모노', '치파오', '한복', '아오자이'],
    correctIndex: 2,
  },
  {
    id: 'world-largest-desert',
    category: '일반상식',
    question: '세계에서 가장 넓은 사막은?',
    choices: ['사하라 사막', '고비 사막', '아라비아 사막', '남극 사막'],
    correctIndex: 3,
  },
  {
    id: 'cult-coffee-origin',
    category: '문화',
    question: '커피의 원산지로 알려진 나라는?',
    choices: ['브라질', '콜롬비아', '에티오피아', '베트남'],
    correctIndex: 2,
  },
  {
    id: 'sci-sun-color',
    category: '과학',
    question: '태양빛이 모두 합쳐졌을 때 실제로 보이는 색은?',
    choices: ['노란색', '주황색', '하얀색', '빨간색'],
    correctIndex: 2,
  },

  // ── 한국상식 40 ───────────────────────────────────────────────
  {
    id: 'kr-largest-island',
    category: '한국상식',
    question: '한국에서 가장 큰 섬은?',
    choices: ['제주도', '거제도', '강화도', '울릉도'],
    correctIndex: 0,
  },
  {
    id: 'kr-second-city',
    category: '한국상식',
    question: '한국에서 인구가 두 번째로 많은 도시는?',
    choices: ['인천', '부산', '대구', '광주'],
    correctIndex: 1,
  },
  {
    id: 'kr-jeju-status',
    category: '한국상식',
    question: '제주의 정식 행정 명칭은?',
    choices: ['제주도', '제주광역시', '제주특별자치도', '제주특별시'],
    correctIndex: 2,
  },
  {
    id: 'kr-baekje-last-capital',
    category: '한국상식',
    question: '백제의 마지막 수도(현재의 부여)는?',
    choices: ['한성', '웅진', '평양', '사비'],
    correctIndex: 3,
  },
  {
    id: 'kr-silla-capital',
    category: '한국상식',
    question: '신라의 수도였던 도시는?',
    choices: ['경주', '개성', '부여', '평양'],
    correctIndex: 0,
  },
  {
    id: 'kr-taegeukgi-trigrams',
    category: '한국상식',
    question: '태극기의 사괘(四卦)가 상징하는 것은?',
    choices: ['동서남북', '천지수화', '봄여름가을겨울', '인의예지'],
    correctIndex: 1,
  },
  {
    id: 'kr-sejong-father',
    category: '한국상식',
    question: '세종대왕의 아버지인 조선 3대 왕은?',
    choices: ['태조', '정종', '태종', '단종'],
    correctIndex: 2,
  },
  {
    id: 'kr-hansando-tactic',
    category: '한국상식',
    question: '한산도 대첩에서 이순신이 사용한 진법은?',
    choices: ['어린진', '첨자진', '안행진', '학익진'],
    correctIndex: 3,
  },
  {
    id: 'kr-honcheonui',
    category: '한국상식',
    question: '천체의 운행을 관측하던 조선의 기구는?',
    choices: ['혼천의', '측우기', '자격루', '앙부일구'],
    correctIndex: 0,
  },
  {
    id: 'kr-rain-gauge',
    category: '한국상식',
    question: '세종 때 만들어진 세계 최초 우량계는?',
    choices: ['혼천의', '측우기', '자격루', '앙부일구'],
    correctIndex: 1,
  },
  {
    id: 'kr-water-clock',
    category: '한국상식',
    question: '장영실이 만든 자동 물시계는?',
    choices: ['혼천의', '측우기', '자격루', '앙부일구'],
    correctIndex: 2,
  },
  {
    id: 'kr-sundial',
    category: '한국상식',
    question: '솥 모양의 조선시대 해시계 이름은?',
    choices: ['혼천의', '측우기', '자격루', '앙부일구'],
    correctIndex: 3,
  },
  {
    id: 'kr-chuseok',
    category: '한국상식',
    question: '추석은 음력 며칠?',
    choices: ['8월 15일', '7월 7일', '9월 9일', '10월 10일'],
    correctIndex: 0,
  },
  {
    id: 'kr-seollal',
    category: '한국상식',
    question: '설날은 음력 며칠?',
    choices: ['12월 31일', '1월 1일', '1월 15일', '2월 1일'],
    correctIndex: 1,
  },
  {
    id: 'kr-daeboreum',
    category: '한국상식',
    question: '정월 대보름은 음력 며칠?',
    choices: ['1월 1일', '2월 15일', '1월 15일', '8월 15일'],
    correctIndex: 2,
  },
  {
    id: 'kr-dano',
    category: '한국상식',
    question: '단오는 음력 며칠?',
    choices: ['3월 3일', '7월 7일', '9월 9일', '5월 5일'],
    correctIndex: 3,
  },
  {
    id: 'kr-bibimbap-city',
    category: '한국상식',
    question: '비빔밥으로 가장 유명한 도시는?',
    choices: ['전주', '광주', '안동', '대구'],
    correctIndex: 0,
  },
  {
    id: 'kr-andong-food',
    category: '한국상식',
    question: '안동의 대표 향토 음식은?',
    choices: ['수원갈비', '안동찜닭', '춘천닭갈비', '의정부부대찌개'],
    correctIndex: 1,
  },
  {
    id: 'kr-gayageum',
    category: '한국상식',
    question: '가야금의 현 개수는?',
    choices: ['6현', '9현', '12현', '24현'],
    correctIndex: 2,
  },
  {
    id: 'kr-geomungo',
    category: '한국상식',
    question: '거문고의 현 개수는?',
    choices: ['12현', '9현', '4현', '6현'],
    correctIndex: 3,
  },
  {
    id: 'kr-anthem-composer',
    category: '한국상식',
    question: '애국가의 작곡가는?',
    choices: ['안익태', '홍난파', '윤이상', '박두진'],
    correctIndex: 0,
  },
  {
    id: 'kr-national-flower',
    category: '한국상식',
    question: '대한민국의 나라꽃은?',
    choices: ['진달래', '무궁화', '개나리', '매화'],
    correctIndex: 1,
  },
  {
    id: 'kr-pansori-five',
    category: '한국상식',
    question: '판소리 다섯 마당에 속하는 작품은?',
    choices: ['구운몽', '홍길동전', '춘향가', '양반전'],
    correctIndex: 2,
  },
  {
    id: 'kr-dokdo-province',
    category: '한국상식',
    question: '독도가 행정구역상 속한 도(道)는?',
    choices: ['강원도', '경상남도', '전라남도', '경상북도'],
    correctIndex: 3,
  },
  {
    id: 'kr-three-kingdoms',
    category: '한국상식',
    question: '삼국시대의 세 나라는?',
    choices: ['고구려·백제·신라', '고구려·발해·신라', '백제·신라·가야', '고구려·백제·가야'],
    correctIndex: 0,
  },
  {
    id: 'kr-goryeo-founder',
    category: '한국상식',
    question: '고려를 건국한 인물은?',
    choices: ['견훤', '왕건', '궁예', '김부식'],
    correctIndex: 1,
  },
  {
    id: 'kr-silla-unifier',
    category: '한국상식',
    question: '삼국 통일을 완수한 신라의 왕은?',
    choices: ['진흥왕', '무열왕', '문무왕', '신문왕'],
    correctIndex: 2,
  },
  {
    id: 'kr-hwarang',
    category: '한국상식',
    question: '화랑은 어느 나라의 청년 조직?',
    choices: ['고구려', '백제', '가야', '신라'],
    correctIndex: 3,
  },
  {
    id: 'kr-tripitaka-temple',
    category: '한국상식',
    question: '팔만대장경이 보관된 사찰은?',
    choices: ['해인사', '불국사', '통도사', '송광사'],
    correctIndex: 0,
  },
  {
    id: 'kr-bulguksa-city',
    category: '한국상식',
    question: '불국사가 위치한 도시는?',
    choices: ['부여', '경주', '공주', '안동'],
    correctIndex: 1,
  },
  {
    id: 'kr-armistice-year',
    category: '한국상식',
    question: '6·25 전쟁의 정전 협정이 체결된 해는?',
    choices: ['1945년', '1948년', '1953년', '1950년'],
    correctIndex: 2,
  },
  {
    id: 'kr-dongji-food',
    category: '한국상식',
    question: '동지에 먹는 한국 전통 음식은?',
    choices: ['떡국', '송편', '부럼', '팥죽'],
    correctIndex: 3,
  },
  {
    id: 'kr-songpyeon-day',
    category: '한국상식',
    question: '송편을 먹는 명절은?',
    choices: ['추석', '설날', '단오', '동지'],
    correctIndex: 0,
  },
  {
    id: 'kr-tteokguk-day',
    category: '한국상식',
    question: '떡국을 먹는 명절은?',
    choices: ['추석', '설날', '단오', '한식'],
    correctIndex: 1,
  },
  {
    id: 'kr-special-self-city',
    category: '한국상식',
    question: '대한민국의 특별자치시는?',
    choices: ['인천', '대전', '세종', '광주'],
    correctIndex: 2,
  },
  {
    id: 'kr-changdeok-unesco',
    category: '한국상식',
    question: '조선 5대 궁궐 중 유네스코 세계유산인 곳은?',
    choices: ['경복궁', '덕수궁', '창경궁', '창덕궁'],
    correctIndex: 3,
  },
  {
    id: 'kr-gyeongbok-builder',
    category: '한국상식',
    question: '경복궁을 처음 지은 조선의 왕은?',
    choices: ['태조', '세종', '태종', '성종'],
    correctIndex: 0,
  },
  {
    id: 'kr-pyeongchang-olympics',
    category: '한국상식',
    question: '평창 동계올림픽이 개최된 해는?',
    choices: ['2014년', '2018년', '2016년', '2022년'],
    correctIndex: 1,
  },
  {
    id: 'kr-seoul-olympics',
    category: '한국상식',
    question: '서울 하계올림픽이 개최된 해는?',
    choices: ['1984년', '1992년', '1988년', '2002년'],
    correctIndex: 2,
  },
  {
    id: 'kr-2002-worldcup',
    category: '한국상식',
    question: '한일 월드컵이 개최된 해는?',
    choices: ['1998년', '2006년', '2010년', '2002년'],
    correctIndex: 3,
  },

  // ── 일반상식 40 ───────────────────────────────────────────────
  {
    id: 'world-uk-capital',
    category: '일반상식',
    question: '영국의 수도는?',
    choices: ['런던', '파리', '베를린', '마드리드'],
    correctIndex: 0,
  },
  {
    id: 'world-germany-capital',
    category: '일반상식',
    question: '독일의 수도는?',
    choices: ['뮌헨', '베를린', '함부르크', '본'],
    correctIndex: 1,
  },
  {
    id: 'world-japan-capital',
    category: '일반상식',
    question: '일본의 수도는?',
    choices: ['오사카', '교토', '도쿄', '요코하마'],
    correctIndex: 2,
  },
  {
    id: 'world-china-capital',
    category: '일반상식',
    question: '중국의 수도는?',
    choices: ['상하이', '홍콩', '광저우', '베이징'],
    correctIndex: 3,
  },
  {
    id: 'world-russia-capital',
    category: '일반상식',
    question: '러시아의 수도는?',
    choices: ['모스크바', '상트페테르부르크', '키예프', '민스크'],
    correctIndex: 0,
  },
  {
    id: 'world-italy-capital',
    category: '일반상식',
    question: '이탈리아의 수도는?',
    choices: ['밀라노', '로마', '베네치아', '피렌체'],
    correctIndex: 1,
  },
  {
    id: 'world-spain-capital',
    category: '일반상식',
    question: '스페인의 수도는?',
    choices: ['바르셀로나', '세비야', '마드리드', '발렌시아'],
    correctIndex: 2,
  },
  {
    id: 'world-canada-capital',
    category: '일반상식',
    question: '캐나다의 수도는?',
    choices: ['토론토', '몬트리올', '밴쿠버', '오타와'],
    correctIndex: 3,
  },
  {
    id: 'world-australia-capital',
    category: '일반상식',
    question: '호주의 수도는?',
    choices: ['캔버라', '시드니', '멜버른', '퍼스'],
    correctIndex: 0,
  },
  {
    id: 'world-brazil-capital',
    category: '일반상식',
    question: '브라질의 수도는?',
    choices: ['상파울루', '브라질리아', '리우데자네이루', '살바도르'],
    correctIndex: 1,
  },
  {
    id: 'world-thailand-capital',
    category: '일반상식',
    question: '태국의 수도는?',
    choices: ['푸껫', '치앙마이', '방콕', '파타야'],
    correctIndex: 2,
  },
  {
    id: 'world-vietnam-capital',
    category: '일반상식',
    question: '베트남의 수도는?',
    choices: ['호치민', '다낭', '하이퐁', '하노이'],
    correctIndex: 3,
  },
  {
    id: 'world-india-capital',
    category: '일반상식',
    question: '인도의 수도는?',
    choices: ['뉴델리', '뭄바이', '콜카타', '첸나이'],
    correctIndex: 0,
  },
  {
    id: 'world-egypt-capital',
    category: '일반상식',
    question: '이집트의 수도는?',
    choices: ['알렉산드리아', '카이로', '룩소르', '기자'],
    correctIndex: 1,
  },
  {
    id: 'world-turkey-capital',
    category: '일반상식',
    question: '튀르키예(터키)의 수도는?',
    choices: ['이스탄불', '이즈미르', '앙카라', '안탈리아'],
    correctIndex: 2,
  },
  {
    id: 'world-largest-country',
    category: '일반상식',
    question: '면적이 가장 넓은 나라는?',
    choices: ['중국', '미국', '캐나다', '러시아'],
    correctIndex: 3,
  },
  {
    id: 'world-most-populous',
    category: '일반상식',
    question: '인구가 가장 많은 나라는? (2025년 기준)',
    choices: ['인도', '중국', '미국', '인도네시아'],
    correctIndex: 0,
  },
  {
    id: 'world-largest-continent',
    category: '일반상식',
    question: '면적이 가장 넓은 대륙은?',
    choices: ['아프리카', '아시아', '북아메리카', '유럽'],
    correctIndex: 1,
  },
  {
    id: 'world-smallest-continent',
    category: '일반상식',
    question: '면적이 가장 작은 대륙은? (남극 제외)',
    choices: ['유럽', '남아메리카', '오세아니아', '북아메리카'],
    correctIndex: 2,
  },
  {
    id: 'world-largest-lake',
    category: '일반상식',
    question: '면적이 가장 큰 호수는?',
    choices: ['바이칼호', '빅토리아호', '슈피리어호', '카스피해'],
    correctIndex: 3,
  },
  {
    id: 'world-deepest-lake',
    category: '일반상식',
    question: '세계에서 가장 깊은 호수는?',
    choices: ['바이칼호', '카스피해', '빅토리아호', '탕가니카호'],
    correctIndex: 0,
  },
  {
    id: 'world-amazon-country',
    category: '일반상식',
    question: '아마존강이 가장 길게 흐르는 나라는?',
    choices: ['페루', '브라질', '콜롬비아', '베네수엘라'],
    correctIndex: 1,
  },
  {
    id: 'world-nile-mouth',
    category: '일반상식',
    question: '나일강이 흘러 들어가는 바다는?',
    choices: ['홍해', '인도양', '지중해', '흑해'],
    correctIndex: 2,
  },
  {
    id: 'world-uk-currency',
    category: '일반상식',
    question: '영국의 통화는?',
    choices: ['유로', '달러', '크로네', '파운드'],
    correctIndex: 3,
  },
  {
    id: 'world-japan-currency',
    category: '일반상식',
    question: '일본의 통화는?',
    choices: ['엔', '위안', '원', '동(VND)'],
    correctIndex: 0,
  },
  {
    id: 'world-eu-currency',
    category: '일반상식',
    question: '유럽연합의 공식 통화는?',
    choices: ['파운드', '유로', '마르크', '프랑'],
    correctIndex: 1,
  },
  {
    id: 'world-china-currency',
    category: '일반상식',
    question: '중국의 공식 통화는?',
    choices: ['엔', '원', '위안', '루블'],
    correctIndex: 2,
  },
  {
    id: 'world-india-currency',
    category: '일반상식',
    question: '인도의 통화는?',
    choices: ['디나르', '동(VND)', '페소', '루피'],
    correctIndex: 3,
  },
  {
    id: 'world-russia-currency',
    category: '일반상식',
    question: '러시아의 통화는?',
    choices: ['루블', '루피', '리라', '디나르'],
    correctIndex: 0,
  },
  {
    id: 'world-un-headquarters',
    category: '일반상식',
    question: 'UN 본부가 있는 도시는?',
    choices: ['워싱턴 D.C.', '뉴욕', '제네바', '브뤼셀'],
    correctIndex: 1,
  },
  {
    id: 'world-eu-headquarters',
    category: '일반상식',
    question: '유럽연합(EU) 본부가 있는 도시는?',
    choices: ['파리', '베를린', '브뤼셀', '빈'],
    correctIndex: 2,
  },
  {
    id: 'world-fifa-headquarters',
    category: '일반상식',
    question: 'FIFA 본부가 있는 도시는?',
    choices: ['파리', '런던', '마드리드', '취리히'],
    correctIndex: 3,
  },
  {
    id: 'world-first-modern-olympics',
    category: '일반상식',
    question: '1896년 첫 근대 올림픽이 열린 도시는?',
    choices: ['아테네', '파리', '런던', '로마'],
    correctIndex: 0,
  },
  {
    id: 'world-greenwich',
    category: '일반상식',
    question: '본초자오선이 지나는 영국의 천문대는?',
    choices: ['옥스퍼드', '그리니치', '케임브리지', '에든버러'],
    correctIndex: 1,
  },
  {
    id: 'world-suez-canal',
    category: '일반상식',
    question: '수에즈 운하가 있는 나라는?',
    choices: ['사우디아라비아', '튀르키예', '이집트', '이라크'],
    correctIndex: 2,
  },
  {
    id: 'world-panama-canal',
    category: '일반상식',
    question: '파나마 운하가 잇는 두 바다는?',
    choices: ['인도양·태평양', '대서양·인도양', '북극해·태평양', '대서양·태평양'],
    correctIndex: 3,
  },
  {
    id: 'world-gibraltar-continents',
    category: '일반상식',
    question: '지브롤터 해협을 사이에 둔 두 대륙은?',
    choices: ['유럽·아프리카', '아시아·유럽', '아프리카·아시아', '북·남아메리카'],
    correctIndex: 0,
  },
  {
    id: 'world-bosphorus-country',
    category: '일반상식',
    question: '보스포러스 해협이 있는 나라는?',
    choices: ['그리스', '튀르키예', '이탈리아', '이집트'],
    correctIndex: 1,
  },
  {
    id: 'world-largest-island',
    category: '일반상식',
    question: '세계에서 가장 큰 섬은? (대륙 제외)',
    choices: ['마다가스카르', '뉴기니', '그린란드', '보르네오'],
    correctIndex: 2,
  },
  {
    id: 'world-eiffel-country',
    category: '일반상식',
    question: '에펠탑이 있는 나라는?',
    choices: ['영국', '독일', '미국', '프랑스'],
    correctIndex: 3,
  },

  // ── 과학 40 ───────────────────────────────────────────────────
  {
    id: 'sci-au',
    category: '과학',
    question: '금의 원소 기호는?',
    choices: ['Au', 'Ag', 'Pb', 'Pt'],
    correctIndex: 0,
  },
  {
    id: 'sci-ag',
    category: '과학',
    question: '은의 원소 기호는?',
    choices: ['Au', 'Ag', 'Al', 'As'],
    correctIndex: 1,
  },
  {
    id: 'sci-fe',
    category: '과학',
    question: '철의 원소 기호는?',
    choices: ['Cu', 'Cr', 'Fe', 'Co'],
    correctIndex: 2,
  },
  {
    id: 'sci-cu',
    category: '과학',
    question: '구리의 원소 기호는?',
    choices: ['Cr', 'Co', 'Ca', 'Cu'],
    correctIndex: 3,
  },
  {
    id: 'sci-na',
    category: '과학',
    question: '나트륨(소듐)의 원소 기호는?',
    choices: ['Na', 'K', 'N', 'S'],
    correctIndex: 0,
  },
  {
    id: 'sci-h',
    category: '과학',
    question: '수소의 원소 기호는?',
    choices: ['He', 'H', 'Hg', 'Hf'],
    correctIndex: 1,
  },
  {
    id: 'sci-co2-formula',
    category: '과학',
    question: '이산화탄소의 화학식은?',
    choices: ['CO', 'NO₂', 'CO₂', 'O₂'],
    correctIndex: 2,
  },
  {
    id: 'sci-salt-formula',
    category: '과학',
    question: '소금(염화나트륨)의 화학식은?',
    choices: ['KCl', 'NaOH', 'HCl', 'NaCl'],
    correctIndex: 3,
  },
  {
    id: 'sci-mars-color',
    category: '과학',
    question: '화성이 붉게 보이는 주된 원인은?',
    choices: ['산화철', '얼음', '메탄가스', '모래'],
    correctIndex: 0,
  },
  {
    id: 'sci-largest-planet',
    category: '과학',
    question: '태양계에서 가장 큰 행성은?',
    choices: ['지구', '목성', '토성', '천왕성'],
    correctIndex: 1,
  },
  {
    id: 'sci-smallest-planet',
    category: '과학',
    question: '태양계에서 가장 작은 행성은?',
    choices: ['화성', '금성', '수성', '명왕성'],
    correctIndex: 2,
  },
  {
    id: 'sci-closest-star',
    category: '과학',
    question: '태양 다음으로 가까운 항성은?',
    choices: ['시리우스', '베가', '폴라리스', '프록시마 센타우리'],
    correctIndex: 3,
  },
  {
    id: 'sci-moon-distance',
    category: '과학',
    question: '지구에서 달까지 평균 거리는 약?',
    choices: ['38만km', '3.8만km', '380만km', '3800km'],
    correctIndex: 0,
  },
  {
    id: 'sci-earth-rotation',
    category: '과학',
    question: '지구의 자전 주기는 약?',
    choices: ['12시간', '24시간', '48시간', '7일'],
    correctIndex: 1,
  },
  {
    id: 'sci-earth-orbit',
    category: '과학',
    question: '지구의 공전 주기는 약?',
    choices: ['180일', '30일', '365일', '730일'],
    correctIndex: 2,
  },
  {
    id: 'sci-moon-orbit',
    category: '과학',
    question: '달의 공전 주기는 약?',
    choices: ['7일', '90일', '365일', '27일'],
    correctIndex: 3,
  },
  {
    id: 'sci-andromeda',
    category: '과학',
    question: '우리은하에 가장 가까운 큰 나선은하는?',
    choices: ['안드로메다', '마젤란', '삼각형자리', '처녀자리'],
    correctIndex: 0,
  },
  {
    id: 'sci-heart-chambers',
    category: '과학',
    question: '사람 심장의 방(chamber) 수는?',
    choices: ['2개', '4개', '3개', '5개'],
    correctIndex: 1,
  },
  {
    id: 'sci-teeth-adult',
    category: '과학',
    question: '성인 영구치의 개수는?',
    choices: ['20개', '28개', '32개', '36개'],
    correctIndex: 2,
  },
  {
    id: 'sci-cone-cells',
    category: '과학',
    question: '눈에서 색을 인식하는 시각세포는?',
    choices: ['간상세포', '시신경', '망막세포', '원추세포'],
    correctIndex: 3,
  },
  {
    id: 'sci-pi',
    category: '과학',
    question: '원주율 π의 근삿값은?',
    choices: ['3.14', '2.72', '1.41', '1.62'],
    correctIndex: 0,
  },
  {
    id: 'sci-light-year',
    category: '과학',
    question: '1광년은 어떤 단위?',
    choices: ['시간', '거리', '속도', '에너지'],
    correctIndex: 1,
  },
  {
    id: 'sci-mole',
    category: '과학',
    question: '1몰의 입자 개수(아보가드로 수)는?',
    choices: ['3.14×10²³', '9.81×10²³', '6.02×10²³', '1.60×10⁻¹⁹'],
    correctIndex: 2,
  },
  {
    id: 'sci-newton',
    category: '과학',
    question: '만유인력의 법칙을 발견한 사람은?',
    choices: ['갈릴레이', '케플러', '코페르니쿠스', '뉴턴'],
    correctIndex: 3,
  },
  {
    id: 'sci-einstein',
    category: '과학',
    question: '상대성이론을 정립한 과학자는?',
    choices: ['아인슈타인', '뉴턴', '호킹', '보어'],
    correctIndex: 0,
  },
  {
    id: 'sci-darwin',
    category: '과학',
    question: '자연선택에 의한 진화론을 발표한 사람은?',
    choices: ['라마르크', '다윈', '멘델', '파스퇴르'],
    correctIndex: 1,
  },
  {
    id: 'sci-pasteur',
    category: '과학',
    question: '광견병 백신을 개발한 과학자는?',
    choices: ['코흐', '플레밍', '파스퇴르', '제너'],
    correctIndex: 2,
  },
  {
    id: 'sci-fleming',
    category: '과학',
    question: '페니실린을 발견한 사람은?',
    choices: ['파스퇴르', '코흐', '왓슨', '플레밍'],
    correctIndex: 3,
  },
  {
    id: 'sci-marie-curie',
    category: '과학',
    question: '라듐과 폴로늄을 발견한 과학자는?',
    choices: ['퀴리 부인', '에디슨', '패러데이', '노벨'],
    correctIndex: 0,
  },
  {
    id: 'sci-edison',
    category: '과학',
    question: '백열전구를 상용화한 발명가는?',
    choices: ['테슬라', '에디슨', '벨', '와트'],
    correctIndex: 1,
  },
  {
    id: 'sci-bell',
    category: '과학',
    question: '전화를 발명한 사람은?',
    choices: ['모스', '에디슨', '벨', '마르코니'],
    correctIndex: 2,
  },
  {
    id: 'sci-marconi',
    category: '과학',
    question: '무선전신을 발명한 사람은?',
    choices: ['모스', '벨', '패러데이', '마르코니'],
    correctIndex: 3,
  },
  {
    id: 'sci-gravity-g',
    category: '과학',
    question: '지구 표면에서 중력 가속도 값은 약?',
    choices: ['9.8 m/s²', '4.9 m/s²', '19.6 m/s²', '32 m/s²'],
    correctIndex: 0,
  },
  {
    id: 'sci-water-boil',
    category: '과학',
    question: '1기압에서 물의 끓는점은?',
    choices: ['50°C', '100°C', '150°C', '212°C'],
    correctIndex: 1,
  },
  {
    id: 'sci-water-freeze',
    category: '과학',
    question: '1기압에서 물의 어는점은?',
    choices: ['-10°C', '4°C', '0°C', '10°C'],
    correctIndex: 2,
  },
  {
    id: 'sci-largest-mammal',
    category: '과학',
    question: '지구상에서 가장 큰 포유류는?',
    choices: ['코끼리', '코뿔소', '향유고래', '대왕고래'],
    correctIndex: 3,
  },
  {
    id: 'sci-spider-legs',
    category: '과학',
    question: '거미의 다리 개수는?',
    choices: ['8개', '6개', '10개', '12개'],
    correctIndex: 0,
  },
  {
    id: 'sci-blood-types-abo',
    category: '과학',
    question: 'ABO 혈액형의 종류는?',
    choices: ['2가지', '4가지', '3가지', '8가지'],
    correctIndex: 1,
  },
  {
    id: 'sci-photosynthesis-input',
    category: '과학',
    question: '식물의 광합성에 필요한 기체는?',
    choices: ['산소', '질소', '이산화탄소', '수소'],
    correctIndex: 2,
  },
  {
    id: 'sci-photosynthesis-output',
    category: '과학',
    question: '식물이 광합성으로 내보내는 기체는?',
    choices: ['이산화탄소', '메탄', '수소', '산소'],
    correctIndex: 3,
  },

  // ── 역사 40 ───────────────────────────────────────────────────
  {
    id: 'hist-koguryeo-founder',
    category: '역사',
    question: '고구려를 건국한 인물은?',
    choices: ['주몽', '왕건', '박혁거세', '김수로'],
    correctIndex: 0,
  },
  {
    id: 'hist-silla-founder',
    category: '역사',
    question: '신라를 건국한 인물은?',
    choices: ['주몽', '박혁거세', '온조', '견훤'],
    correctIndex: 1,
  },
  {
    id: 'hist-baekje-founder',
    category: '역사',
    question: '백제를 건국한 인물은?',
    choices: ['주몽', '박혁거세', '온조', '비류'],
    correctIndex: 2,
  },
  {
    id: 'hist-goryeo-year',
    category: '역사',
    question: '고려가 건국된 해는?',
    choices: ['676년', '1392년', '1592년', '918년'],
    correctIndex: 3,
  },
  {
    id: 'hist-joseon-year',
    category: '역사',
    question: '조선이 건국된 해는?',
    choices: ['1392년', '918년', '1492년', '1592년'],
    correctIndex: 0,
  },
  {
    id: 'hist-imjin',
    category: '역사',
    question: '임진왜란이 일어난 해는?',
    choices: ['1392년', '1592년', '1492년', '1636년'],
    correctIndex: 1,
  },
  {
    id: 'hist-byeongja',
    category: '역사',
    question: '병자호란이 일어난 해는?',
    choices: ['1592년', '1627년', '1636년', '1894년'],
    correctIndex: 2,
  },
  {
    id: 'hist-donghak',
    category: '역사',
    question: '동학 농민 운동이 일어난 해는?',
    choices: ['1882년', '1905년', '1910년', '1894년'],
    correctIndex: 3,
  },
  {
    id: 'hist-japan-annex',
    category: '역사',
    question: '한일 병합(국권 피탈)이 일어난 해는?',
    choices: ['1910년', '1905년', '1907년', '1919년'],
    correctIndex: 0,
  },
  {
    id: 'hist-march-1',
    category: '역사',
    question: '3·1 운동이 일어난 해는?',
    choices: ['1910년', '1919년', '1929년', '1945년'],
    correctIndex: 1,
  },
  {
    id: 'hist-liberation',
    category: '역사',
    question: '한국이 일제로부터 광복한 날은?',
    choices: ['1948년 8월 15일', '1945년 5월 5일', '1945년 8월 15일', '1950년 6월 25일'],
    correctIndex: 2,
  },
  {
    id: 'hist-korea-establish',
    category: '역사',
    question: '대한민국 정부가 수립된 해는?',
    choices: ['1945년', '1950년', '1953년', '1948년'],
    correctIndex: 3,
  },
  {
    id: 'hist-419',
    category: '역사',
    question: '4·19 혁명이 일어난 해는?',
    choices: ['1960년', '1958년', '1962년', '1972년'],
    correctIndex: 0,
  },
  {
    id: 'hist-yu-gwan-sun',
    category: '역사',
    question: '유관순 열사가 만세운동을 이끈 곳은?',
    choices: ['평양', '천안', '서울', '부산'],
    correctIndex: 1,
  },
  {
    id: 'hist-french-revolution',
    category: '역사',
    question: '프랑스 혁명이 일어난 해는?',
    choices: ['1776년', '1815년', '1789년', '1848년'],
    correctIndex: 2,
  },
  {
    id: 'hist-american-independence',
    category: '역사',
    question: '미국 독립선언이 발표된 해는?',
    choices: ['1492년', '1789년', '1812년', '1776년'],
    correctIndex: 3,
  },
  {
    id: 'hist-columbus',
    category: '역사',
    question: '콜럼버스가 신대륙에 도착한 해는?',
    choices: ['1492년', '1453년', '1521년', '1607년'],
    correctIndex: 0,
  },
  {
    id: 'hist-ww1-start',
    category: '역사',
    question: '제1차 세계대전이 시작된 해는?',
    choices: ['1905년', '1914년', '1910년', '1918년'],
    correctIndex: 1,
  },
  {
    id: 'hist-ww1-end',
    category: '역사',
    question: '제1차 세계대전이 끝난 해는?',
    choices: ['1914년', '1916년', '1918년', '1920년'],
    correctIndex: 2,
  },
  {
    id: 'hist-ww2-start',
    category: '역사',
    question: '제2차 세계대전이 시작된 해는?',
    choices: ['1933년', '1937년', '1941년', '1939년'],
    correctIndex: 3,
  },
  {
    id: 'hist-bastille',
    category: '역사',
    question: '프랑스 혁명의 시작을 알린 사건은?',
    choices: ['바스티유 습격', '베르사유 행진', '단두대 처형', '나폴레옹 즉위'],
    correctIndex: 0,
  },
  {
    id: 'hist-waterloo',
    category: '역사',
    question: '나폴레옹이 패배한 마지막 전투는?',
    choices: ['트라팔가', '워털루', '아우스터리츠', '라이프치히'],
    correctIndex: 1,
  },
  {
    id: 'hist-russia-revolution',
    category: '역사',
    question: '러시아 10월 혁명이 일어난 해는?',
    choices: ['1905년', '1922년', '1917년', '1939년'],
    correctIndex: 2,
  },
  {
    id: 'hist-berlin-wall-fall',
    category: '역사',
    question: '베를린 장벽이 무너진 해는?',
    choices: ['1985년', '1991년', '1993년', '1989년'],
    correctIndex: 3,
  },
  {
    id: 'hist-soviet-collapse',
    category: '역사',
    question: '소련이 해체된 해는?',
    choices: ['1991년', '1989년', '1993년', '1995년'],
    correctIndex: 0,
  },
  {
    id: 'hist-renaissance-origin',
    category: '역사',
    question: '르네상스가 시작된 나라는?',
    choices: ['프랑스', '이탈리아', '영국', '독일'],
    correctIndex: 1,
  },
  {
    id: 'hist-industrial-rev',
    category: '역사',
    question: '산업혁명이 처음 시작된 나라는?',
    choices: ['프랑스', '독일', '영국', '미국'],
    correctIndex: 2,
  },
  {
    id: 'hist-rome-fall-west',
    category: '역사',
    question: '서로마 제국이 멸망한 해는?',
    choices: ['313년', '1054년', '1453년', '476년'],
    correctIndex: 3,
  },
  {
    id: 'hist-east-roman-fall',
    category: '역사',
    question: '동로마(비잔틴) 제국이 멸망한 해는?',
    choices: ['1453년', '476년', '1054년', '1492년'],
    correctIndex: 0,
  },
  {
    id: 'hist-china-qin',
    category: '역사',
    question: '중국을 처음 통일한 황제는?',
    choices: ['한무제', '진시황', '당태종', '명태조'],
    correctIndex: 1,
  },
  {
    id: 'hist-china-prc',
    category: '역사',
    question: '중화인민공화국이 수립된 해는?',
    choices: ['1911년', '1937년', '1949년', '1976년'],
    correctIndex: 2,
  },
  {
    id: 'hist-meiji-restoration',
    category: '역사',
    question: '일본 메이지 유신이 일어난 해는?',
    choices: ['1853년', '1894년', '1905년', '1868년'],
    correctIndex: 3,
  },
  {
    id: 'hist-koryo-religion',
    category: '역사',
    question: '고려시대에 가장 융성했던 종교는?',
    choices: ['불교', '유교', '도교', '천주교'],
    correctIndex: 0,
  },
  {
    id: 'hist-joseon-religion',
    category: '역사',
    question: '조선의 통치 이념은?',
    choices: ['불교', '유교', '도교', '천주교'],
    correctIndex: 1,
  },
  {
    id: 'hist-sado',
    category: '역사',
    question: '정조의 아버지로 뒤주에 갇혀 죽은 세자는?',
    choices: ['효명세자', '소현세자', '사도세자', '양녕대군'],
    correctIndex: 2,
  },
  {
    id: 'hist-noryang',
    category: '역사',
    question: '이순신이 전사한 임진왜란 마지막 해전은?',
    choices: ['한산도해전', '명량해전', '부산포해전', '노량해전'],
    correctIndex: 3,
  },
  {
    id: 'hist-myeongryang',
    category: '역사',
    question: '이순신이 13척으로 승리한 해전은?',
    choices: ['명량해전', '한산도해전', '노량해전', '옥포해전'],
    correctIndex: 0,
  },
  {
    id: 'hist-paper-invent',
    category: '역사',
    question: '종이를 처음 만든 나라는?',
    choices: ['이집트', '중국', '그리스', '인도'],
    correctIndex: 1,
  },
  {
    id: 'hist-printing-gutenberg',
    category: '역사',
    question: '활판 인쇄술을 유럽에 보급한 사람은?',
    choices: ['마르코폴로', '콜럼버스', '구텐베르크', '갈릴레이'],
    correctIndex: 2,
  },
  {
    id: 'hist-magna-carta',
    category: '역사',
    question: '영국 마그나카르타가 서명된 해는?',
    choices: ['1066년', '1453년', '1492년', '1215년'],
    correctIndex: 3,
  },

  // ── 문화 40 ───────────────────────────────────────────────────
  {
    id: 'cult-starry-night',
    category: '문화',
    question: '"별이 빛나는 밤"을 그린 화가는?',
    choices: ['반 고흐', '모네', '고갱', '세잔'],
    correctIndex: 0,
  },
  {
    id: 'cult-sunflowers',
    category: '문화',
    question: '"해바라기" 연작으로 유명한 화가는?',
    choices: ['세잔', '반 고흐', '모네', '마네'],
    correctIndex: 1,
  },
  {
    id: 'cult-impression',
    category: '문화',
    question: '인상주의(인상파)라는 이름의 유래가 된 화가는?',
    choices: ['마네', '르누아르', '모네', '드가'],
    correctIndex: 2,
  },
  {
    id: 'cult-water-lilies',
    category: '문화',
    question: '"수련" 연작으로 유명한 화가는?',
    choices: ['고흐', '피카소', '마티스', '모네'],
    correctIndex: 3,
  },
  {
    id: 'cult-guernica',
    category: '문화',
    question: '"게르니카"를 그린 화가는?',
    choices: ['피카소', '미로', '달리', '마티스'],
    correctIndex: 0,
  },
  {
    id: 'cult-dali-clocks',
    category: '문화',
    question: '흘러내리는 시계로 유명한 초현실주의 화가는?',
    choices: ['피카소', '달리', '마그리트', '칸딘스키'],
    correctIndex: 1,
  },
  {
    id: 'cult-sistine',
    category: '문화',
    question: '시스티나 성당의 천장화를 그린 화가는?',
    choices: ['다빈치', '라파엘로', '미켈란젤로', '도나텔로'],
    correctIndex: 2,
  },
  {
    id: 'cult-david-statue',
    category: '문화',
    question: '"다비드상"을 조각한 사람은?',
    choices: ['도나텔로', '베르니니', '로댕', '미켈란젤로'],
    correctIndex: 3,
  },
  {
    id: 'cult-thinker',
    category: '문화',
    question: '조각상 "생각하는 사람"의 작가는?',
    choices: ['로댕', '미켈란젤로', '베르니니', '도나텔로'],
    correctIndex: 0,
  },
  {
    id: 'cult-the-scream',
    category: '문화',
    question: '"절규"를 그린 화가는?',
    choices: ['클림트', '뭉크', '쇠라', '마티스'],
    correctIndex: 1,
  },
  {
    id: 'cult-kiss-klimt',
    category: '문화',
    question: '"키스"(황금색 명화)를 그린 화가는?',
    choices: ['뭉크', '모네', '클림트', '마네'],
    correctIndex: 2,
  },
  {
    id: 'cult-beethoven-9',
    category: '문화',
    question: '베토벤 교향곡 제9번의 별명은?',
    choices: ['영웅', '운명', '전원', '합창'],
    correctIndex: 3,
  },
  {
    id: 'cult-beethoven-5',
    category: '문화',
    question: '베토벤 교향곡 제5번의 별명은?',
    choices: ['운명', '영웅', '합창', '전원'],
    correctIndex: 0,
  },
  {
    id: 'cult-beethoven-3',
    category: '문화',
    question: '베토벤 교향곡 제3번의 별명은?',
    choices: ['전원', '영웅', '운명', '합창'],
    correctIndex: 1,
  },
  {
    id: 'cult-mozart-magic',
    category: '문화',
    question: '모차르트의 "마술피리"는 어떤 장르?',
    choices: ['교향곡', '협주곡', '오페라', '소나타'],
    correctIndex: 2,
  },
  {
    id: 'cult-bach-aria',
    category: '문화',
    question: '"G선상의 아리아"를 작곡한 사람은?',
    choices: ['헨델', '비발디', '모차르트', '바흐'],
    correctIndex: 3,
  },
  {
    id: 'cult-vivaldi-fourseasons',
    category: '문화',
    question: '"사계"를 작곡한 작곡가는?',
    choices: ['비발디', '바흐', '모차르트', '헨델'],
    correctIndex: 0,
  },
  {
    id: 'cult-schubert-erlking',
    category: '문화',
    question: '가곡 "마왕"을 작곡한 사람은?',
    choices: ['슈만', '슈베르트', '브람스', '멘델스존'],
    correctIndex: 1,
  },
  {
    id: 'cult-tchaikovsky-swan',
    category: '문화',
    question: '발레 음악 "백조의 호수"의 작곡가는?',
    choices: ['베토벤', '모차르트', '차이콥스키', '라흐마니노프'],
    correctIndex: 2,
  },
  {
    id: 'cult-don-quixote',
    category: '문화',
    question: '"돈키호테"를 쓴 작가는?',
    choices: ['단테', '괴테', '셰익스피어', '세르반테스'],
    correctIndex: 3,
  },
  {
    id: 'cult-divine-comedy',
    category: '문화',
    question: '"신곡"을 쓴 작가는?',
    choices: ['단테', '페트라르카', '보카치오', '호메로스'],
    correctIndex: 0,
  },
  {
    id: 'cult-iliad',
    category: '문화',
    question: '"일리아드"의 저자로 알려진 사람은?',
    choices: ['베르길리우스', '호메로스', '헤로도토스', '플라톤'],
    correctIndex: 1,
  },
  {
    id: 'cult-faust',
    category: '문화',
    question: '"파우스트"를 쓴 독일 작가는?',
    choices: ['헤르만 헤세', '토마스 만', '괴테', '카프카'],
    correctIndex: 2,
  },
  {
    id: 'cult-war-peace',
    category: '문화',
    question: '"전쟁과 평화"를 쓴 러시아 작가는?',
    choices: ['도스토옙스키', '푸시킨', '체호프', '톨스토이'],
    correctIndex: 3,
  },
  {
    id: 'cult-crime-punishment',
    category: '문화',
    question: '"죄와 벌"을 쓴 작가는?',
    choices: ['도스토옙스키', '톨스토이', '푸시킨', '고골'],
    correctIndex: 0,
  },
  {
    id: 'cult-old-man-sea',
    category: '문화',
    question: '"노인과 바다"를 쓴 작가는?',
    choices: ['포크너', '헤밍웨이', '피츠제럴드', '스타인벡'],
    correctIndex: 1,
  },
  {
    id: 'cult-1984',
    category: '문화',
    question: '소설 "1984"를 쓴 작가는?',
    choices: ['헉슬리', '카뮈', '조지 오웰', '사르트르'],
    correctIndex: 2,
  },
  {
    id: 'cult-harry-potter',
    category: '문화',
    question: '"해리포터" 시리즈의 작가는?',
    choices: ['톨킨', '루이스', '가이먼', 'J.K. 롤링'],
    correctIndex: 3,
  },
  {
    id: 'cult-lord-of-rings',
    category: '문화',
    question: '"반지의 제왕"을 쓴 작가는?',
    choices: ['톨킨', '롤링', 'C.S. 루이스', 'G.R.R. 마틴'],
    correctIndex: 0,
  },
  {
    id: 'cult-baseball-innings',
    category: '문화',
    question: '야구 한 경기의 정규 이닝 수는?',
    choices: ['7이닝', '9이닝', '11이닝', '12이닝'],
    correctIndex: 1,
  },
  {
    id: 'cult-soccer-players',
    category: '문화',
    question: '축구 한 팀이 한 경기에 출전하는 인원은?',
    choices: ['9명', '10명', '11명', '12명'],
    correctIndex: 2,
  },
  {
    id: 'cult-volleyball-players',
    category: '문화',
    question: '배구 한 팀이 코트에 서는 인원은?',
    choices: ['5명', '7명', '9명', '6명'],
    correctIndex: 3,
  },
  {
    id: 'cult-basketball-players',
    category: '문화',
    question: '농구 한 팀이 코트에 서는 인원은?',
    choices: ['5명', '3명', '6명', '7명'],
    correctIndex: 0,
  },
  {
    id: 'cult-rugby-players',
    category: '문화',
    question: '럭비 15인제의 한 팀 출전 인원은?',
    choices: ['11명', '15명', '13명', '18명'],
    correctIndex: 1,
  },
  {
    id: 'cult-marathon-distance',
    category: '문화',
    question: '정식 마라톤의 공식 거리는?',
    choices: ['40km', '50km', '42.195km', '100km'],
    correctIndex: 2,
  },
  {
    id: 'cult-tokyo-olympics-2020',
    category: '문화',
    question: '2020 하계 올림픽 개최 도시는? (실제 개최 2021)',
    choices: ['베이징', '파리', '리우', '도쿄'],
    correctIndex: 3,
  },
  {
    id: 'cult-paris-olympics-2024',
    category: '문화',
    question: '2024 하계 올림픽 개최 도시는?',
    choices: ['파리', '도쿄', '로스앤젤레스', '베이징'],
    correctIndex: 0,
  },
  {
    id: 'cult-qatar-worldcup',
    category: '문화',
    question: '2022 FIFA 월드컵 개최국은?',
    choices: ['러시아', '카타르', '미국', '호주'],
    correctIndex: 1,
  },
  {
    id: 'cult-pizza-origin',
    category: '문화',
    question: '피자의 원산지로 알려진 나라는?',
    choices: ['프랑스', '그리스', '이탈리아', '미국'],
    correctIndex: 2,
  },
  {
    id: 'cult-sushi-origin',
    category: '문화',
    question: '초밥(스시)의 원산지로 알려진 나라는?',
    choices: ['중국', '한국', '베트남', '일본'],
    correctIndex: 3,
  },
] as const;

// Stable, sorted-by-id view used by the seed-based picker. Sorting at module load
// pins the pick order regardless of array insertion order — adding a new question
// at the end of TRIVIA_POOL will *not* change the seed→question mapping for any
// id that was already there (only the slot a new id occupies in alphabetical order).
export const TRIVIA_POOL_SORTED: readonly TriviaQuestion[] = [...TRIVIA_POOL].sort((a, b) =>
  a.id < b.id ? -1 : a.id > b.id ? 1 : 0,
);

export function getQuestionById(id: string): TriviaQuestion | undefined {
  return TRIVIA_POOL.find((q) => q.id === id);
}
